// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYmHToZKfDVv1Sy0AIMxRa-zUXm51GbMs',
    appId: '1:643950016422:web:278209c3790bce96784167',
    messagingSenderId: '643950016422',
    projectId: 'talk-with-hands',
    authDomain: 'talk-with-hands.firebaseapp.com',
    storageBucket: 'talk-with-hands.firebasestorage.app',
    measurementId: 'G-7J487HHSW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPe5QUqCHskJqwt3W8Lfh-71AjyoO-q4',
    appId: '1:643950016422:android:42f29853a3b4187f784167',
    messagingSenderId: '643950016422',
    projectId: 'talk-with-hands',
    storageBucket: 'talk-with-hands.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu1HVkYsDmrYcMz-tDOIre-YZ20X6jWjU',
    appId: '1:643950016422:ios:6ec02264156c4e38784167',
    messagingSenderId: '643950016422',
    projectId: 'talk-with-hands',
    storageBucket: 'talk-with-hands.firebasestorage.app',
    iosBundleId: 'com.example.signLanguageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu1HVkYsDmrYcMz-tDOIre-YZ20X6jWjU',
    appId: '1:643950016422:ios:6ec02264156c4e38784167',
    messagingSenderId: '643950016422',
    projectId: 'talk-with-hands',
    storageBucket: 'talk-with-hands.firebasestorage.app',
    iosBundleId: 'com.example.signLanguageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYmHToZKfDVv1Sy0AIMxRa-zUXm51GbMs',
    appId: '1:643950016422:web:ff0b3cad7e4c6e90784167',
    messagingSenderId: '643950016422',
    projectId: 'talk-with-hands',
    authDomain: 'talk-with-hands.firebaseapp.com',
    storageBucket: 'talk-with-hands.firebasestorage.app',
    measurementId: 'G-Q4H15NEGM6',
  );
}
